export default {
  // gameUI
  GAMEUI_INIT_GAME: 'GAMEUI_INIT_GAME',
  GAMEUI_NOT_INITED: 'GAMEUI_NOT_INITED',
  
  // socketConnection
  SOCKET_CONNECTION_INIT: 'SOCKET_CONNECTION_INIT',
  SOCKET_CONNECTION_START: 'SOCKET_CONNECTION_START',
  SOCKET_CONNECTION_SUCCEEDED: 'SOCKET_CONNECTION_SUCCEEDED',
  SOCKET_CONNECTION_FAILED: 'SOCKET_CONNECTION_FAILED',
};